### ISSUE TITLE
please link slides from the ICES VI "ABC" session

### ISSUE THREAD

**Issue by skolenik** [mcconvil/ices2021_mase_demo#1]
https://ww2.amstat.org/meetings/ices/2021/onlineprogram/AbstractDetails.cfm?AbstractID=307933

**Comment by mcconvil** [comment]
Good suggestion!  Added: https://github.com/mcconvil/ices2021_mase_demo/blob/main/AI%20Models%20in%20Survey%20Estimation.pdf
